---
date: 2020/01/30
tag:
  - rstats
---

# 2019-nCoV
## 2019-nCov outbreak data
Script to extract latest 2019-nCov outbreak data from [dxy.cn](dxy.cn). **Manually updated (`r Sys.Date()`)** 

Date source: https://3g.dxy.cn/newh5/view/pneumonia
```{r}
library(rvest)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(jsonlite)

pneumonia <- read_html("https://3g.dxy.cn/newh5/view/pneumonia")
AreaStat <- pneumonia %>% html_nodes("#getAreaStat") %>% html_text() %>%
    str_replace("try \\{ window.getAreaStat =", "") %>%
    str_replace("\\}catch\\(e\\)\\{\\}", "") %>%
    fromJSON %>%
    rename(confirmedCount_sum = confirmedCount,
           suspectedCount_sum = suspectedCount,
           curedCount_sum = curedCount,
           deadCount_sum = deadCount) %>%
    unnest(cities, keep_empty = T)

ChinaStat <- pneumonia %>% html_nodes("#getListByCountryTypeService1") %>% html_text() %>%
    str_replace("try \\{ window.getListByCountryTypeService1 =", "") %>%
    str_replace("\\}catch\\(e\\)\\{\\}", "") %>%
    fromJSON

IntStat <- pneumonia %>% html_nodes("#getListByCountryTypeService2") %>% html_text() %>%
    str_replace("try \\{ window.getListByCountryTypeService2 =", "") %>%
    str_replace("\\}catch\\(e\\)\\{\\}", "") %>%
    fromJSON

SumStat <- pneumonia %>% html_nodes("#getStatisticsService") %>% html_text() %>%
    str_replace("try \\{ window.getStatisticsService =", "") %>%
    str_replace("\\}catch\\(e\\)\\{\\}", "") %>%
    fromJSON

write_csv(AreaStat, paste0("data/AreaStat_dxy_", gsub("[ :]", "_", Sys.time()), ".csv"))
write_csv(ChinaStat, paste0("data/ChinaStat_dxy_", gsub("[ :]", "_", Sys.time()), ".csv"))
write_csv(IntStat, paste0("data/IntStat_dxy_", gsub("[ :]", "_", Sys.time()), ".csv"))

```

Epidemic report for China
```{r}
library(knitr)
kable(head(ChinaStat))
```

Epidemic report for outside of China
```{r}
kable(head(IntStat))
```

Download the data: 
[/data](https://github.com/hutuben/hutuben.github.io/tree/master/data)

## Epidemic map by `leaflet`
```{r}
library(leaflet)
##devtools::install_github("lchiffon/leafletCN")
library(leafletCN)
library(RColorBrewer)
library(htmltools)
library(htmlwidgets)
ChinaStat$province <- c(
    "Tibet Autonomous Region",
    "Hubei",
    "Guangdong",
    "Zhejiang",
    "Beijing",
    "Shanghai",
    "Hunan",
    "Anhui",
    "Chongqing",
    "Sichuan",
    "Shandong",
    "Guangxi Zhuang Autonomous Region",
    "Fujian",
    "Jiangsu",
    "Henan",
    "Hainan",
    "Tianjin",
    "Jiangxi",
    "Shaanxi",
    "Guizhou",
    "Liaoning",
    "Hong Kong Special Administrative Region",
    "Heilongjiang",
    "Macao Special Administrative Region",
    "Xinjiang Uygur Autonomous Region",
    "Gansu province",
    "Yunnan",
    "Taiwan",
    "Shanxi",
    "Jilin",
    "Hebei",
    "Ningxia Hui Autonomous Region",
    "Inner Mongolia Autonomous Region",
    "Qinghai")
map = leafletGeo("china", ChinaStat, namevar = ~provinceName, valuevar = ~confirmedCount)
ChinaStat$provinceName[c(22, 24, 28)] <- c("香港特别行政区", "澳门特别行政区", "台湾省")
map@data <- map@data %>% left_join(ChinaStat, by = c("name" = "provinceName"))

bins <- c(1, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("YlOrRd", domain = map$value, bins = bins)
labs <- mapply(function(n, x, y, z, h){
    HTML(paste0(n, "<br>",
                "confirmedCount: ", x, "<br>",
                "curedCount: ", y, "<br>",
                "deadCount: ", z, "<br>",
                "updated: ", as.POSIXct(h / 1000, origin="1970-01-01")))
}, paste0(map$name, "(", map$province, ")"),
map$confirmedCount, map$curedCount, map$deadCount, map$modifyTime,
SIMPLIFY = FALSE, USE.NAMES = FALSE) ## must no name

ll <- leaflet(map) %>% addTiles() %>%
    addPolygons(stroke = TRUE,
                smoothFactor = 1,
                fillOpacity = 0.7,
                weight = 1,
                fillColor = ~pal(value),
                color = "white",
                label = labs
                ) %>%    
    addLegend("bottomright", pal = pal, values = ~value,
              title = "confirmedCount") %>%
    addTitle(paste("2019-nCoV<br>",
                        "Confirmed Count:", SumStat$confirmedCount, "<br>",
                        "Suspected Count", SumStat$suspectedCount, "<br>",
                        "Cured Count:", SumStat$curedCount, "<br>",
                        "Dead Count:", SumStat$deadCount, "<br>",
                        "Updated:", as.POSIXct(SumStat$modifyTime / 1000,
                                               origin="1970-01-01")
                  ), fontSize = "12px",
             leftPosition = 80)

saveWidget(ll, "nCoV2019.html")
file.rename("nCoV2019.html", "widgets/nCoV2019.html")

```

[/widgets/nCoV2019.html](/widgets/nCoV2019.html) (reload to show)

<iframeComp ihtml="/widgets/nCoV2019.html"></iframeComp>



```{r}
cmap <- leafletGeo("city")
AS <- AreaStat %>% filter(!provinceName %in% c("北京市", "上海市", "天津市", "重庆市", "香港", "台湾", "澳门"))
AS$cityName[which(AS$cityName == "神农架林区")] <- "神农架"
cmap@data <- cmap@data %>% left_join(na.omit(AS), by = c("name" = "cityName"))
cmap@data[is.na(cmap@data)] <- 0
cmap@data[cmap@data$name=="北京", 11:14] <- ChinaStat[ChinaStat$provinceName=="北京市", 10:13]
cmap@data[cmap@data$name=="上海", 11:14] <- ChinaStat[ChinaStat$provinceName=="上海市", 10:13]
cmap@data[cmap@data$name=="天津", 11:14] <- ChinaStat[ChinaStat$provinceName=="天津市", 10:13]
cmap@data[cmap@data$name=="重庆", 11:14] <- ChinaStat[ChinaStat$provinceName=="重庆市", 10:13]
cmap@data[cmap@data$name=="香港", 11:14] <- ChinaStat[ChinaStat$provinceName=="香港特别行政区", 10:13]
cmap@data[cmap@data$name=="澳门", 11:14] <- ChinaStat[ChinaStat$provinceName=="澳门特别行政区", 10:13]

cmap@data[385, 11:14] <- ChinaStat[22, 10:13]

clabs <- mapply(function(n, x, y, z, h){
    HTML(paste0(n, "<br>",
                "confirmedCount: ", x, "<br>",
                "curedCount: ", y, "<br>",
                "deadCount: ", z, "<br>"))
}, cmap$name, cmap$confirmedCount, cmap$curedCount, cmap$deadCount,
SIMPLIFY = FALSE, USE.NAMES = FALSE) ## must no name

llc <- leaflet(cmap) %>% addTiles() %>%
    addPolygons(stroke = TRUE,
                smoothFactor = 1,
                fillOpacity = 0.7,
                weight = 1,
                fillColor = ~pal(confirmedCount),
                color = "white",
                label = clabs
                ) %>%    
    addLegend("bottomright", pal = pal, values = ~confirmedCount,
              title = "confirmedCount") %>%
    addTitle(paste("2019-nCoV (mainland cities)<br>",
                        "Confirmed Count:", SumStat$confirmedCount, "<br>",
                        "Suspected Count", SumStat$suspectedCount, "<br>",
                        "Cured Count:", SumStat$curedCount, "<br>",
                        "Dead Count:", SumStat$deadCount, "<br>"),
             fontSize = "12px",
             leftPosition = 80)

saveWidget(llc, "nCoV2019_cities.html")
file.rename("nCoV2019_cities.html", "widgets/nCoV2019_cities.html")

```

[/widgets/nCoV2019_cities.html](/widgets/nCoV2019_cities.html) (reload to show)

<iframeComp ihtml="/widgets/nCoV2019_cities.html"></iframeComp>

**More links:**

More detailed maps from Johns Hopkins: <https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6>

WHO situation reports: <https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/>

github wuhan2020 project: <https://github.com/wuhan2020/wuhan2020>
